#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.9.5 on Tue Apr  7 19:42:05 2020
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
import gettext
from MainFrame import MainFrame


class PancakeViewerApp(wx.App):
    def OnInit(self):
        self.mainFrame = MainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.mainFrame)
        self.mainFrame.Show()
        return True

# end of class PancakeViewerApp

if __name__ == "__main__":
    gettext.install("pancakeViewerApp") # replace with the appropriate catalog name

    pancakeViewerApp = PancakeViewerApp(0)
    pancakeViewerApp.MainLoop()
